org: alonsobenitess2
service: api-auth

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true

provider:
  name: aws
  runtime: python3.10
  memorySize: 1024
  timeout: 20
  iam:
    role: arn:aws:iam::295655809569:role/LabRole
  environment:
    USUARIOS_TABLE: ${sls:stage}-t_clientes
    STAFF_TABLE: ${sls:stage}-t_staff
    INVITATION_CODES_TABLE: ${sls:stage}-t_invitation_codes
    JWT_SECRET: ${env:JWT_SECRET, 'utec'}

package:
  patterns:
    - "!./**"
    - "*.py"
    - "requirements.txt"
    - "!package.json"
    - "!node_modules/**"
    - "!venv/**"
    - "!test/**"
    - "!.git/**"

functions:
  crearUsuario:
    handler: CrearUsuario.lambda_handler
    events:
      - http:
          path: /auth/registro
          method: post
          cors: true

  loginUsuario:
    handler: LoginUsuario.lambda_handler
    events:
      - http:
          path: /auth/login
          method: post
          cors: true

  logoutUsuario:
    handler: LogoutUsuario.lambda_handler
    events:
      - http:
          path: /auth/logout
          method: post
          cors: true

  generarInvitationCode:  
    handler: GenerarInvitationCode.lambda_handler
    events:
      - http:
          path: /auth/generate-invitation
          method: post
          cors: true

resources:
  Resources:
    TablaClientes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USUARIOS_TABLE}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    TablaStaff:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.STAFF_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant_id_sede
            AttributeType: S
          - AttributeName: email 
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id_sede 
            KeyType: HASH
          - AttributeName: email 
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    TablaInvitationCodes:  
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.INVITATION_CODES_TABLE}
        AttributeDefinitions:
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: code
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true